### ISSUE TITLE
Macro error when expanding partial function

### ISSUE THREAD

**Issue by smithjessk** [storm-enroute/coroutines#19]
Demo code: https://git.io/vrHmh

As recommended in #15, I'm porting some of the tests from Async into Coroutines. I translated [this test](https://github.com/scala/async/blob/master/src/test/scala/scala/async/run/toughtype/ToughType.scala#L38) and discovered a `NullPointerException` during compilation. A truncated SBT dump is at the bottom of this issue.
I believe this may be related to @retronym's [comment](https://github.com/storm-enroute/coroutines/issues/15#issuecomment-173425582) in #15. I will investigate this more soon; just wanted to go ahead and bring the issue up.

```
> test
[info] Compiling 1 Scala source to /home/jess/projects/coroutines/target/scala-2.11/test-classes...
[info] Run completed in 20 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] /home/jess/projects/coroutines/src/test/scala/org/coroutines/async-await-tests.scala:65: exception during macro expansion: 
[error] java.lang.NullPointerException
[error] 	at org.coroutines.Analyzer$class.isCoroutineDefMarker(Analyzer.scala:328)
[error] 	at org.coroutines.Synthesizer.isCoroutineDefMarker(Synthesizer.scala:15)
[error] 	at org.coroutines.ThreeAddressFormTransformation$NestedContextValidator.traverse(ThreeAddressFormTransformation.scala:48)
[error] 	at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1232)
[error] 	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1323)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[error] 	at org.coroutines.ThreeAddressFormTransformation$NestedContextValidator.traverse(ThreeAddressFormTransformation.scala:62)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
[error] 	at scala.reflect.api.Trees$Traverser.traverseCases(Trees.scala:2487)
[error] 	at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1258)
[error] 	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1323)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
```

**Comment by smithjessk** [comment]
Found another partial function error. 
Not sure if the canonicalization or Async/Await is the problem, but I'll log the bug here.

Note that `AsyncAwait` is as defined [here](https://github.com/smithjessk/coroutines/blob/00f77027e0011c19f60d070397bdeb9701b6bc42/coroutines-extra/src/main/scala/AsyncAwait.scala). 

```scala
test("compilation error in partial function") {
    val c: Coroutine._0[(Future[Any], AsyncAwait.Cell[Any]), Any] = coroutine { () =>
      try {
        sys.error("error"))
        AsyncAwait.await(Future("ho"))
      } catch {
        case e: RuntimeException => AsyncAwait.await(Future("oh"))
        case _ => AsyncAwait.await(Future("ho"))
      }
      AsyncAwait.await(Future("oh"))
    }
    val future = AsyncAwait.async(c)
    assert(Await.result(future, 1 seconds) == "oh")
  }
```

I omitted part of the stack trace, but here is the core of it:

```
[error] exception during macro expansion: 
[error] scala.reflect.macros.TypecheckException: type mismatch;
[error]  found   : Unit
[error]  required: String
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:34)

...

[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] 	at org.coroutines.AstCanonicalization$class.canonicalizeTree(AstCanonicalization.scala:453)
[error] 	at org.coroutines.Synthesizer.canonicalizeTree(Synthesizer.scala:15)
[error] 	at org.coroutines.Synthesizer.synthesize(Synthesizer.scala:310)
[error] 	at org.coroutines.Coroutine$.synthesize(Coroutine.scala:259)
[error]     val c: Coroutine._0[(Future[Any], AsyncAwait.Cell[Any]), Any] = coroutine { () =>
```

**Comment by smithjessk** [comment]
[This call](https://github.com/smithjessk/coroutines/blob/26a45b301e9fd45ad3dc3c140b63a3c1acf8d397/src/main/scala/org/coroutines/AstCanonicalization.scala#L48) to `isCoroutineDefMarker` is problematic because `typer.typeOf(co) == null`. Thus, I doubt that the issue is related to @retronym's [comment](https://github.com/storm-enroute/coroutines/issues/15#issuecomment-173425582).

**Comment by smithjessk** [comment]
[This test](https://github.com/smithjessk/coroutines/blob/de7c47e7a9608d5429175f45680903747bc16147/src/test/scala/org/coroutines/async-await-tests.scala#L404) generates this problematic [`rawlambda`](https://github.com/smithjessk/coroutines/blob/de7c47e7a9608d5429175f45680903747bc16147/src/main/scala/org/coroutines/AstCanonicalization.scala#L439): 

```scala
raw = (() => {
  val f: PartialFunction[Int,Int] = (({
    class $anonfun extends scala.runtime.AbstractPartialFunction[Int,Int] with Serializable {
      def <init>(): <$anon: Int => Int> = {
        $anonfun.super.<init>();
        ()
      };
      final override def applyOrElse[A1 <: Int, B1 >: Int](x1: A1, default: A1 => B1): B1 = ((x1.asInstanceOf[Int]: Int): Int @unchecked) match {
        case (x @ _) => x.+(1)
        case (defaultCase$ @ _) => default.apply(x1)
      };
      final def isDefinedAt(x1: Int): Boolean = ((x1.asInstanceOf[Int]: Int): Int @unchecked) match {
        case (x @ _) => true
        case (defaultCase$ @ _) => false
      }
    };
    new $anonfun()
  }: PartialFunction[Int,Int]): PartialFunction[Int,Int]);
  AsyncAwaitTest.await[Int].apply[(scala.concurrent.Future[Int], org.coroutines.AsyncAwaitTest.Cell[Int]), Int](scala.concurrent.Future.apply[Int](f.apply(2))(scala.concurrent.ExecutionContext.Implicits.global))(Predef.this.=:=.tpEquals[((scala.concurrent.Future[Int], org.coroutines.AsyncAwaitTest.Cell[Int]), Int)])
})
```

Canonicalization fails when going over `default.apply(x1)`. 

`typer.typeOf(co) == null` because `default` is never added to `typer.treeMapping` and `co.tpe == null`. `default` is never added because [this case](https://github.com/smithjessk/coroutines/blob/de7c47e7a9608d5429175f45680903747bc16147/coroutines-common/src/main/scala/scala/coroutines/common/TraverserUtil.scala#L26) does not cause traversal of the second cases inside the above partial functions.

**Comment by axel22** [comment]
Can you extend traverser to correctly cover the other cases?

**Comment by smithjessk** [comment]
Yes! I'm working on it in [this branch](https://github.com/smithjessk/coroutines/tree/fix-partial-function-transformation).

**Comment by smithjessk** [comment]
It is not the second case that is dropped by the [quasiquotes](https://github.com/smithjessk/coroutines/blob/de7c47e7a9608d5429175f45680903747bc16147/coroutines-common/src/main/scala/scala/coroutines/common/TraverserUtil.scala#L26). Rather, it is the default case, e.g.: 
```scala
case (defaultCase$ @ _) => default.apply(x1)
```

For instance, see that this partial function:
```scala
val f = { 
  case x: Int => x + 1
  case x: String => x.length 
}: PartialFunction[Any, Int]
```

has the following [values](https://github.com/smithjessk/coroutines/blob/de7c47e7a9608d5429175f45680903747bc16147/coroutines-common/src/main/scala/scala/coroutines/common/TraverserUtil.scala#L26) for `cs0` and `cs1`, respectively:
```scala
List(case (x @ (_: scala.Int)) => x.+(1), case (x @ (_: scala.this.Predef.String)) => x.length())
List(case (x @ (_: Int)) => x.+(1), case (x @ (_: String)) => x.length())
```

Thus, we might want to stop canonicalization for the default cases.

**Comment by axel22** [comment]
Add a `println` statement to `case _` in `TraverserUtil`. The anonymous partial function class was not traversed by it for some reason. Find out why, fix `TraverserUtil`, and this should work.

**Comment by smithjessk** [comment]
I think I'm misunderstanding your statement.

The [partial function case](https://github.com/smithjessk/coroutines/blob/de7c47e7a9608d5429175f45680903747bc16147/coroutines-common/src/main/scala/scala/coroutines/common/TraverserUtil.scala#L26) matches on the anonymous partial function. This call to traverse is caused by the [ascription case](https://github.com/smithjessk/coroutines/blob/de7c47e7a9608d5429175f45680903747bc16147/coroutines-common/src/main/scala/scala/coroutines/common/TraverserUtil.scala#L73), in which `e0` is the anonymous class that extends `AbstractPartialFunction`. 

`println("t0 = " + t0)` inside the PF case prints the following output:

```scala
t0 = ({
  final <synthetic> class $anonfun extends scala.runtime.AbstractPartialFunction[Int,Int] with Serializable {
    def <init>() = {
      super.<init>();
      ()
    };
    final override def applyOrElse[A1 <: Int, B1 >: Int](x1: A1, default: scala.this.Function1[A1, B1]) = ((x1.asInstanceOf[Int]: Int): (x1.asInstanceOf[Int]: Int): @scala.unchecked) match {
      case (x @ _) => x.+(1)
      case (defaultCase$ @ _) => default.apply(x1)
    };
    final def isDefinedAt(x1: Int): Boolean = ((x1.asInstanceOf[Int]: Int): (x1.asInstanceOf[Int]: Int): @scala.unchecked) match {
      case (x @ _) => true
      case (defaultCase$ @ _) => false
    }
  };
  new $anonfun()
}: PartialFunction[Int,Int])
```

However, `defaultCase` is not a part of `cs0`.
